// Copyright (c) 2018 Uber Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/m3db/m3ctl/service/r2/store/go

package store

import (
	"github.com/m3db/m3metrics/rules"
	"github.com/m3db/m3metrics/rules/models"

	"github.com/golang/mock/gomock"
)

// Mock of Store interface
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *_MockStoreRecorder
}

// Recorder for MockStore (not exported)
type _MockStoreRecorder struct {
	mock *MockStore
}

func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &_MockStoreRecorder{mock}
	return mock
}

func (_m *MockStore) EXPECT() *_MockStoreRecorder {
	return _m.recorder
}

func (_m *MockStore) FetchNamespaces() (*models.NamespacesView, error) {
	ret := _m.ctrl.Call(_m, "FetchNamespaces")
	ret0, _ := ret[0].(*models.NamespacesView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockStoreRecorder) FetchNamespaces() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "FetchNamespaces")
}

func (_m *MockStore) ValidateRuleSet(rs *models.RuleSetSnapshotView) error {
	ret := _m.ctrl.Call(_m, "ValidateRuleSet", rs)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockStoreRecorder) ValidateRuleSet(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ValidateRuleSet", arg0)
}

func (_m *MockStore) CreateNamespace(namespaceID string, uOpts UpdateOptions) (*models.NamespaceView, error) {
	ret := _m.ctrl.Call(_m, "CreateNamespace", namespaceID, uOpts)
	ret0, _ := ret[0].(*models.NamespaceView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockStoreRecorder) CreateNamespace(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreateNamespace", arg0, arg1)
}

func (_m *MockStore) DeleteNamespace(namespaceID string, uOpts UpdateOptions) error {
	ret := _m.ctrl.Call(_m, "DeleteNamespace", namespaceID, uOpts)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockStoreRecorder) DeleteNamespace(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteNamespace", arg0, arg1)
}

func (_m *MockStore) FetchRuleSet(namespaceID string) (rules.RuleSet, error) {
	ret := _m.ctrl.Call(_m, "FetchRuleSet", namespaceID)
	ret0, _ := ret[0].(rules.RuleSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockStoreRecorder) FetchRuleSet(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "FetchRuleSet", arg0)
}

func (_m *MockStore) FetchRuleSetSnapshot(namespaceID string) (*models.RuleSetSnapshotView, error) {
	ret := _m.ctrl.Call(_m, "FetchRuleSetSnapshot", namespaceID)
	ret0, _ := ret[0].(*models.RuleSetSnapshotView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockStoreRecorder) FetchRuleSetSnapshot(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "FetchRuleSetSnapshot", arg0)
}

func (_m *MockStore) FetchMappingRule(namespaceID string, mappingRuleID string) (*models.MappingRuleView, error) {
	ret := _m.ctrl.Call(_m, "FetchMappingRule", namespaceID, mappingRuleID)
	ret0, _ := ret[0].(*models.MappingRuleView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockStoreRecorder) FetchMappingRule(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "FetchMappingRule", arg0, arg1)
}

func (_m *MockStore) CreateMappingRule(namespaceID string, mrv *models.MappingRuleView, uOpts UpdateOptions) (*models.MappingRuleView, error) {
	ret := _m.ctrl.Call(_m, "CreateMappingRule", namespaceID, mrv, uOpts)
	ret0, _ := ret[0].(*models.MappingRuleView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockStoreRecorder) CreateMappingRule(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreateMappingRule", arg0, arg1, arg2)
}

func (_m *MockStore) UpdateMappingRule(namespaceID string, mappingRuleID string, mrv *models.MappingRuleView, uOpts UpdateOptions) (*models.MappingRuleView, error) {
	ret := _m.ctrl.Call(_m, "UpdateMappingRule", namespaceID, mappingRuleID, mrv, uOpts)
	ret0, _ := ret[0].(*models.MappingRuleView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockStoreRecorder) UpdateMappingRule(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "UpdateMappingRule", arg0, arg1, arg2, arg3)
}

func (_m *MockStore) DeleteMappingRule(namespaceID string, mappingRuleID string, uOpts UpdateOptions) error {
	ret := _m.ctrl.Call(_m, "DeleteMappingRule", namespaceID, mappingRuleID, uOpts)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockStoreRecorder) DeleteMappingRule(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteMappingRule", arg0, arg1, arg2)
}

func (_m *MockStore) FetchMappingRuleHistory(namespaceID string, mappingRuleID string) ([]*models.MappingRuleView, error) {
	ret := _m.ctrl.Call(_m, "FetchMappingRuleHistory", namespaceID, mappingRuleID)
	ret0, _ := ret[0].([]*models.MappingRuleView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockStoreRecorder) FetchMappingRuleHistory(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "FetchMappingRuleHistory", arg0, arg1)
}

func (_m *MockStore) FetchRollupRule(namespaceID string, rollupRuleID string) (*models.RollupRuleView, error) {
	ret := _m.ctrl.Call(_m, "FetchRollupRule", namespaceID, rollupRuleID)
	ret0, _ := ret[0].(*models.RollupRuleView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockStoreRecorder) FetchRollupRule(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "FetchRollupRule", arg0, arg1)
}

func (_m *MockStore) CreateRollupRule(namespaceID string, rrv *models.RollupRuleView, uOpts UpdateOptions) (*models.RollupRuleView, error) {
	ret := _m.ctrl.Call(_m, "CreateRollupRule", namespaceID, rrv, uOpts)
	ret0, _ := ret[0].(*models.RollupRuleView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockStoreRecorder) CreateRollupRule(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreateRollupRule", arg0, arg1, arg2)
}

func (_m *MockStore) UpdateRollupRule(namespaceID string, rollupRuleID string, rrv *models.RollupRuleView, uOpts UpdateOptions) (*models.RollupRuleView, error) {
	ret := _m.ctrl.Call(_m, "UpdateRollupRule", namespaceID, rollupRuleID, rrv, uOpts)
	ret0, _ := ret[0].(*models.RollupRuleView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockStoreRecorder) UpdateRollupRule(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "UpdateRollupRule", arg0, arg1, arg2, arg3)
}

func (_m *MockStore) DeleteRollupRule(namespaceID string, rollupRuleID string, uOpts UpdateOptions) error {
	ret := _m.ctrl.Call(_m, "DeleteRollupRule", namespaceID, rollupRuleID, uOpts)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockStoreRecorder) DeleteRollupRule(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteRollupRule", arg0, arg1, arg2)
}

func (_m *MockStore) FetchRollupRuleHistory(namespaceID string, rollupRuleID string) ([]*models.RollupRuleView, error) {
	ret := _m.ctrl.Call(_m, "FetchRollupRuleHistory", namespaceID, rollupRuleID)
	ret0, _ := ret[0].([]*models.RollupRuleView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockStoreRecorder) FetchRollupRuleHistory(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "FetchRollupRuleHistory", arg0, arg1)
}

func (_m *MockStore) UpdateRuleSet(rs rules.MutableRuleSet) (rules.RuleSet, error) {
	ret := _m.ctrl.Call(_m, "UpdateRuleSet", rs)
	ret0, _ := ret[0].(rules.RuleSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockStoreRecorder) UpdateRuleSet(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "UpdateRuleSet", arg0)
}

func (_m *MockStore) Close() {
	_m.ctrl.Call(_m, "Close")
}

func (_mr *_MockStoreRecorder) Close() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Close")
}
